package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.triggers.vcs
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Hosted_BuildPublicRepo'
in the project with id = 'Hosted', and delete the patch script.
*/
create(RelativeId("Hosted"), BuildType({
    id("Hosted_BuildPublicRepo")
    name = "Build (public repo)"

    vcs {
        root(RelativeId("Hosted_Http101289361kilinaNomasterGitRefsHeadsDevelop"))
    }

    triggers {
        vcs {
        }
    }
}))

