package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.projectFeatures.GitLabIssueTracker
import jetbrains.buildServer.configs.kotlin.projectFeatures.gitlabIssues
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with id = 'Cloud'
accordingly, and delete the patch script.
*/
changeProject(RelativeId("Cloud")) {
    features {
        val feature1 = find<GitLabIssueTracker> {
            gitlabIssues {
                id = "PROJECT_EXT_265"
                displayName = "Project without master branch"
                repositoryURL = "https://gitlab.com/n.burnasheva/without-master-branch"
                authType = accessToken {
                    accessToken = "credentialsJSON:2e407222-ca07-486c-ae9d-3a878bea3f45"
                }
            }
        }
        feature1.apply {
        }
    }
}
