package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'Hosted_Http101289361kilinaNomasterGitRefsHeadsDevelop'
in the project with id = 'Hosted', and delete the patch script.
*/
create(RelativeId("Hosted"), GitVcsRoot({
    id("Hosted_Http101289361kilinaNomasterGitRefsHeadsDevelop")
    name = "http://10.128.93.61/kilina/nomaster.git#refs/heads/develop"
    url = "http://10.128.93.61/kilina/nomaster.git"
    branch = "refs/heads/develop"
    branchSpec = "refs/heads/*"
    authMethod = password {
        userName = "jetbrains"
        password = ""
    }
    param("oauthProviderId", "PROJECT_EXT_266")
}))

